### ISSUE TITLE
Add a UUID/unique code for all entities

### ISSUE THREAD

**Issue by devils2ndself** [devils2ndself/unimay-backend#20]
Displaying SQL id's on front-end isn't a good practice, that may also lead to opening opportunities for vulnerabilities, thus it is best to implement another indexing system, like UUID or unique string ID and change every entity's getById to use the new id

**Comment by GGO-web** [comment]
There is not matter, ID's as the numbers are not too bad, do not need to change the entire SQL system just for FE requirements, we will generate UUID using some external libs if necessary. You can close this issue.
